Forum Management System/Forum Management System/Models/Post.cs
using Forum_Management_System.Models.Contracts;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Forum_Management_System.Models
{
    public class Post : TextEntity, IPost
    {
        public Post() : base()
        {

        }

        public Post(int id, int userID, string body, string title, List<Tag> tags, List<PostImage> images) : base(id, userID, body)
        {
            this.Title = title;
            this.Images = images;
            this.Tags = tags;
        }

        [StringLength(64, MinimumLength = 16, ErrorMessage = ErrorMessages.LengthOutofRange)]
        [Required(AllowEmptyStrings = false)]
        public string Title
        {
            get;
            set;
        }

        public ICollection<Comment> Comments { get; set; } = new List<Comment>();

        public ICollection<PostImage> Images { get; set; } = new List<PostImage>();

        public ICollection<Tag> Tags { get; set; } = new List<Tag>();

        public ICollection<PostVote> Votes { get; set; } = new List<PostVote>();

        public void Deconstruct(out int id,
                                out User user,
                                out string title,
                                out string body,
                                out int likes,
                                out int dislikes,
                                out DateTime timeCreated,
                                out ICollection<Comment> comments,
                                out ICollection<PostImage> images)
        {
            this.Deconstruct(out id, out user, out body, out likes, out dislikes, out timeCreated);
            title = this.Title;
            comments = this.Comments;
            images = this.Images;
        }

    }
}

Forum Management System/Forum Management System/Controllers/CommentsController.cs
using Forum_Management_System.Models.Dtos;
using Forum_Management_System.Models.ViewModels;
using Forum_Management_System.Services.Contracts;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace Forum_Management_System.Controllers
{
    public class CommentsController : Controller
    {
        ICommentService commentService;

        public CommentsController(ICommentService commentService)
        {
            this.commentService = commentService;
        }

        [HttpGet("Posts/Details/{postID}/Comments/{id}")]
        public IActionResult Delete(int postID, int id)
        {
            if (!this.HttpContext.Session.Keys.Contains("UserRole"))
            {
                return this.RedirectToAction("Login", "Authentication");
            }
            if (!(this.HttpContext.Session.GetString("UserRole") == "admin"))
            {
                return this.Unauthorized();
            }
            this.commentService.Delete(postID, id);
            return this.RedirectToAction(actionName: "Index", controllerName: "Posts");
        }

        [HttpGet("Posts/Details/{postID}/Comments/{id}/Like")]
        public IActionResult Like(int postID, int id)
        {
            if (!this.IsLoggedIn())
            {
                return this.RedirectToAction("Login", "Authentication");
            }
            this.commentService.Vote(this.GetVote(id, true));
            return this.RedirectToAction(actionName: "Details", controllerName: "Posts", new { id = postID });
        }

        [HttpGet("Posts/Details/{postID}/Comments/{id}/Dislike")]
        public IActionResult Dislike(int postID, int id)
        {
            if (!this.IsLoggedIn())
            {
                return this.RedirectToAction("Login", "Authentication");
            }
            this.commentService.Vote(this.GetVote(id, false));
            return this.RedirectToAction(actionName: "Details", controllerName: "Posts", new { id = postID });
        }

        [HttpPost]
        public IActionResult Create(PostDetailsViewModel viewModel)
        {
            int userID = int.Parse(this.HttpContext.Session.GetString("UserID"));
            var commentDTO = new CommentCreateDTO(userID, viewModel.PostID, viewModel.CommentBody);
            this.commentService.Create(commentDTO);
            return this.RedirectToAction(actionName: "Details", controllerName: "Posts", new { id = viewModel.PostID });
        }
        private bool IsLoggedIn()
        {
            return this.HttpContext.Session.Keys.Contains("Username");
        }

        private bool IsAdmin()
        {
            return this.HttpContext.Session.GetString("UserRole") == "admin";
        }

        private CommentVoteDTO GetVote(int id, bool action)
        {
            int userID = int.Parse(this.HttpContext.Session.GetString("UserID"));
            var vote = new CommentVoteDTO(id, userID, action);
            return vote;
        }
    }
}

Forum Management System/Forum Management System/Controllers/PostsController.cs
using Forum_Management_System.Models.Dtos;
using Forum_Management_System.Models.QueryParameters;
using Forum_Management_System.Models.ViewModels;
using Forum_Management_System.Services.Contracts;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Forum_Management_System.Controllers
{
    public class PostsController : Controller
    {
        private readonly IPostService postService;

        public PostsController(IPostService postService)
        {
            this.postService = postService;
        }

        public IActionResult Index([FromQuery] PostQueryParameters queryParameters)
        {
            var result = this.postService.Get(queryParameters);
            return this.View(result);
        }

        public IActionResult Details(int id)
        {
            if (!this.IsLoggedIn())
            {
                return this.RedirectToAction("Login", "Authentication");
            }
            var postDTO = this.postService.Get(id);
            var result = new PostDetailsViewModel(postDTO, "");
            return this.View(result);
        }

        public IActionResult CreateForm()
        {
            if (!this.ModelState.IsValid)
            {
                return this.View();
            }

            if (!this.IsLoggedIn())
            {
                return this.RedirectToAction("Login", "Authentication");
            }
            return this.View();
        }

        public IActionResult Create(PostCreateDTO dto)
        {
            if (!this.IsLoggedIn())
            {
                return this.RedirectToAction("Login", "Authentication");
            }
            var tags = this.ExtractTags(dto.Body);
            dto = dto with { Tags = tags, ImageURLs = new List<string>(), UserID = this.GetUserID() };
            this.postService.Create(dto);
            return this.RedirectToAction("Index", "Posts");
        }

        public IActionResult Delete(int id)
        {
            if (!this.IsLoggedIn())
            {
                return this.RedirectToAction("Login", "Authentication");
            }
            if (!this.IsAdmin())
            {
                return this.Unauthorized();
            }
            this.postService.Delete(id);
            return this.RedirectToAction(actionName: "Index", controllerName: "Posts");
        }

        public IActionResult Like(int id)
        {
            if (!this.IsLoggedIn())
            {
                return this.RedirectToAction("Login", "Authentication");
            }
            this.postService.Vote(this.GetVote(id, true));
            return this.RedirectToAction("Details", "Posts", new { id });
        }

        public IActionResult Dislike(int id)
        {
            if (!this.IsLoggedIn())
            {
                return this.RedirectToAction("Login", "Authentication");
            }
            this.postService.Vote(this.GetVote(id, false));
            return this.RedirectToAction("Details", "Posts", new { id });
        }

        private bool IsLoggedIn()
        {
            return this.HttpContext.Session.Keys.Contains("Username");
        }

        private int GetUserID()
        {
            return int.Parse(this.HttpContext.Session.GetString("UserID"));
        }

        private bool IsAdmin()
        {
            return this.HttpContext.Session.GetString("UserRole") == "admin";
        }

        private PostVoteDTO GetVote(int id, bool action)
        {
            int userID = int.Parse(this.HttpContext.Session.GetString("UserID"));
            var vote = new PostVoteDTO(id, userID, action);
            return vote;
        }

        public IEnumerable<string> ExtractTags(string body)
        {
            if (!string.IsNullOrEmpty(body))
            {
                var words = body.Split(' ', '\n');
                foreach (var word in words)
                {
                    if (word.Length > 1 && word[0] == '#')
                    {
                        yield return word[1..];
                    }
                }
            }
        }
    }
}

Forum Management System/Forum Management System/Views/Posts/CreateForm.cshtml
@model PostCreateDTO
<body>
    <form asp-controller="Posts" asp-action="Create" method="post">
        <div class="mb-3">
            <label asp-for="Title" class="form-label">Title</label>
            <input asp-for="Title" type="text" class="form-control" placeholder="Title must be betweent 16 and 64 characters." />
		    <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div>
          <label asp-for="Body" class="form-label">Post Body</label>
          <textarea asp-for="Body" class="form-control" placeholder="Body must be at least 32 characters long. To add tags just add them with '#' in the body of the post." id="exampleFormControlTextarea1" rows="7"></textarea>
          <span asp-validation-for="Body" class="text-danger"></span>
        </div>
        <br />
        <input type="submit" value="Create Post" class="btn btn-primary" />
    </form>
</body>

Forum Management System/Forum Management System/Views/Posts/Details.cshtml
@model PostDetailsViewModel
<body>
    @{
        this.ViewData["Title"] = $"Chef Chat - {this.Model.PostDTO.Title.Substring(0, 15)}...";
        this.ViewData["IsAuthenticated"] = this.Context.Session.Keys.Contains("Username");
        this.ViewData["CanDelete"] = this.Context.Session.Keys.Contains("UserRole") && 
                                     this.Context.Session.GetString("UserRole") == "admin";
    }
    <div class="post-details">
    <h1>@this.Model.PostDTO.Title</h1>
    <p>
        @this.Model.PostDTO.TimeCreated 
        @{
            foreach (var tag in this.Model.PostDTO.Tags)
            {
                <span class="badge bg-primary">@tag</span>
            }
        }
    </p>
    <p>@this.Model.PostDTO.Body</p>
    <a asp-controller="Posts" asp-action="Like" asp-route-id="@this.Model.PostDTO.ID" class="btn btn-success">👍 @this.Model.PostDTO.Likes</a>
    <a asp-controller="Posts" asp-action="Dislike" asp-route-id="@this.Model.PostDTO.ID" class="btn btn-danger">👎 @this.Model.PostDTO.Dislikes</a>
    <a asp-controller="Posts" asp-action="Details" asp-route-id="@this.Model.PostDTO.ID" class="btn btn-info">💬 @this.Model.PostDTO.Comments.Count()</a>
    @{
        if(this.ViewData["CanDelete"].ToString() == "True")
        {
            <a asp-controller="Posts" asp-action="Delete" asp-route-id="@this.Model.PostDTO.ID" class="btn btn-sm btn-danger">DELETE</a>
        }
    }
    <hr />
    <form asp-controller="Comments" asp-action=Create method="post">
        <div class="row align-items-end">
            <div class="form-floating">
                <input type="text" asp-for="CommentBody" class="form-control" id="floatingInput" placeholder="I really like what..." aria-describedby="floatingInputHelp" />
                <span asp-validation-for="CommentBody" class="text-danger"></span>
                <label asp-for="CommentBody">Comment</label>
                <div id="floatingInputHelp" class="form-text">Place your comment here and press 'Enter' to submit it.</div>
            </div>
            <div style="display: none">
                <input type="number" asp-for="PostID" value="@this.Model.PostDTO.ID" />
            </div>
            <br />
            <input type="submit" value="Comment" class="btn btn-xs btn-outline-primary" />
        </div>
    </form>

    @{
        foreach(var comment in this.Model.PostDTO.Comments)
        {
            <hr />
            <p><b>@comment.UserUsername</b> - @comment.TimeCreated.ToString("HH:mm dd-MM-yy")</p>
            <p>@comment.Body</p>
            <a href="@this.Model.PostDTO.ID/Comments/@comment.ID/Like" class="btn btn-sm btn-success">👍 @comment.Likes</a>
            <a href="@this.Model.PostDTO.ID/Comments/@comment.ID/Dislike" class="btn btn-sm btn-danger">👎 @comment.Dislikes</a>
            if(this.ViewData["CanDelete"].ToString() == "True")
            {
                <a href="@this.Model.PostDTO.ID/Comments/@comment.ID" class="btn btn-xs btn-danger">DELETE</a>
            }
        }
    }
    </div>
</body>

Forum Management System/Forum Management System/Views/Posts/Index.cshtml
@model IEnumerable<PostResponseInListDTO>
<body>
    @{
        this.ViewData["Title"] = "Chef Chat - Posts";
        this.ViewData["IsAuthenticated"] = this.Context.Session.Keys.Contains("Username");
        var tempSortBy = new List<string>()
    {
    "Recent",
    "RecentActivity",
    "Likes",
    "Comments"
    };

        var tempTimePeriod = new List<string>()
    {
    "Alltime",
    "Today",
    "Yesterday",
    "Lastweek",
    "Lastmonth",
    "Months",
    "Year"
    };
        var sortByList = new SelectList(tempSortBy);
        var timePeriodList = new SelectList(tempTimePeriod);
    }

    <form asp-controller="Posts" asp-action="Index" method="get" class="form-inline">
        <nav class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme"
             id="layout-navbar">
            <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
                <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
                    <i class="bx bx-menu bx-sm"></i>
                </a>
            </div>

            <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">
                <!-- Search -->
                <div class="navbar-nav align-items-center">
                    <div class="nav-item d-flex align-items-center">
                        <i class="bx bx-search fs-4 lh-0"></i>
                        <input type="text"
                               name="Keyword"
                               class="form-control border-0 shadow-none"
                               placeholder="Search..."
                               aria-label="Search..." />
                    </div>
                </div>
                <!-- /Search -->
            </div>
        </nav>
        <div style="padding-left: 6%; padding-right: 6%">
            <br />
            <label>Sort By:</label>
            <select asp-items="@sortByList" name="SortBy" class="form-select"></select>
            <label>Time Period:</label>
            <select asp-items="@timePeriodList" name="TimePeriod" class="form-select"></select>
            <br />
            <input type="submit" value="Search" class="btn btn-primary" />
        </div>
    </form>
    <hr />
    <div class="d-grid gap-2 col-6 mx-auto">
        <a asp-controller="Posts" asp-action="CreateForm" class="btn btn-primary btn-lg" type="button">Create a post</a>
    </div>
    <hr />
    @{
        
        foreach (var post in this.Model)
        {
            <div class="post-in-list">
                <p><a asp-controller="Users" asp-action="DetailsLink" asp-route-id="@post.UserUsername"><span class="badge bg-warning">@post.UserUsername</span></a> - @post.TimeCreated.ToString("HH:mm dd-MM-yy")</p>
                @{
                    if (this.ViewData["IsAuthenticated"].ToString() == "True")
                    {
                        <a asp-controller="Posts" asp-action="Details" asp-route-id="@post.ID" class="nav">@post.Title</a>
                    }
                    else
                    {
                        <a asp-controller="Authentication" asp-action="Login" class="nav">@post.Title</a>
                    }
                }
                <p>
                    @{
                        foreach (var tag in post.Tags)
                        {
                            <span class="badge bg-label-primary">@tag</span>
                        }
                    }
                </p>
                <a asp-controller="Posts" asp-action="Like" asp-route-id="@post.ID" class="btn btn-sm btn-success">👍 @post.Likes</a>
                <a asp-controller="Posts" asp-action="Dislike" asp-route-id="@post.ID" class="btn btn-sm btn-danger">👎 @post.Dislikes</a>
                <a asp-controller="Posts" asp-action="Details" asp-route-id="@post.ID" class="btn btn-sm btn-info">💬 @post.CommentCount</a>
                <hr />
            </div>
        }
    }
</body>