Forum Management System/Forum Management System/Controllers/AdminPanelController.cs
using Forum_Management_System.Controllers.Helpers;
using Forum_Management_System.Dtos.Responses;
using Forum_Management_System.Models;
using Forum_Management_System.Models.QueryParameters;
using Forum_Management_System.Services;
using Forum_Management_System.Services.Contracts;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace Forum_Management_System.Controllers
{
    public class AdminPanelController : Controller
    {
        private readonly IUsersServices usersServices;

        public AdminPanelController(IUsersServices usersServices)
        {
            this.usersServices = usersServices;
        }
        public IActionResult Index([FromQuery] UserQueryParameters parameters)
        {
            var users = this.usersServices.Get(parameters, UserRole.admin) as IEnumerable<UserFullInfoDto>;

            return this.View(model: users);
        }
    }
}

Forum Management System/Forum Management System/Controllers/AuthenticationController.cs
using Forum_Management_System.Controllers.Helpers;
using Forum_Management_System.Dtos.Requests;
using Forum_Management_System.Exceptions;
using Forum_Management_System.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Forum_Management_System.Controllers
{
    public class AuthenticationController : Controller
    {
        private readonly IAuthHelper authHelper;
        private readonly IUsersServices usersServices;
        public AuthenticationController(IAuthHelper authHelper, IUsersServices usersServices)
        {
            this.authHelper = authHelper;
            this.usersServices = usersServices;
        }
        public IActionResult Login()
        {
            if (this.HttpContext.Session.Keys.Any(key => key == "Username"))
            {
                return this.RedirectToAction(actionName: "Index", controllerName: "Home");
            }

            return this.View();
        }

        [HttpPost]
        public IActionResult Login(LoginUserDto userCredentials)
        {
            try
            {
                var user = this.authHelper.TryGetUser(userCredentials.Username, userCredentials.Password);
                this.HttpContext.Session.SetString("Username", user.Username);
                this.HttpContext.Session.SetString("UserID", user.UserID.ToString());
                this.HttpContext.Session.SetString("UserRole", user.Role.ToString());
            }
            catch (NotAuthenticatedOperationException e)
            {
                this.ViewData["Failed"] = e.Message;
                return this.View();
            }

            return this.RedirectToAction(actionName:"Index", controllerName:"Posts");
        }
        public IActionResult Logout()
        {
            this.HttpContext.Session.Clear();
            
            return this.RedirectToAction(actionName: "Index", controllerName: "Home");
        }

        public IActionResult Register()
        {
            if (this.HttpContext.Session.Keys.Any(key => key == "Username"))
            {
                return this.RedirectToAction(actionName: "Index", controllerName: "Posts");
            }

            return this.View();
        }

        [HttpPost]
        public IActionResult Register(CreateUserDto dto)
        {

            try
            {
                var user = this.usersServices.CreateUser(dto);
                this.HttpContext.Session.SetString("Username", user.Username);
                this.HttpContext.Session.SetString("UserRole", user.Role.ToString());
            }
            catch (Exception e)
            {
                this.ViewData["Failed"] = e.Message;
                return this.View();
            }
            return this.RedirectToAction(actionName: "Index", controllerName: "Posts");
        }
    }
}

Forum Management System/Forum Management System/Views/Shared/_Layout.cshtml
@{
    var currentUser = this.Context.Session.GetString("Username");
    var role = this.Context.Session.GetString("UserRole");
}
<!DOCTYPE html>

<html lang="en"
      class="light-style layout-menu-fixed"
      dir="ltr"
      data-theme="theme-default"
      data-assets-path="~/assets/"
      data-template="vertical-menu-template-free">
<head>
    <meta charset="utf-8" />
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />

    <title>@this.ViewData["Title"]</title>

    <meta name="description" content="" />

    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="~/images/logo.png" />

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
          rel="stylesheet" />

    <!-- Icons. Uncomment required icon fonts -->
    <link rel="stylesheet" href="~/assets/vendor/fonts/boxicons.css" />

    <!-- Core CSS -->
    <link rel="stylesheet" href="~/assets/vendor/css/core.css" class="template-customizer-core-css" />
    <link rel="stylesheet" href="~/assets/vendor/css/theme-default.css" class="template-customizer-theme-css" />
    <link rel="stylesheet" href="~/assets/css/demo.css" />

    <!-- Vendors CSS -->
    <link rel="stylesheet" href="~/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css" />

    <link rel="stylesheet" href="~/assets/vendor/libs/apex-charts/apex-charts.css" />

    <!-- Page CSS -->
    <link rel="stylesheet" href="~/css/site.css" />
    <!-- Helpers -->
    <script src="~/assets/vendor/js/helpers.js"></script>

    <!--! Template customizer & Theme config files MUST be included after core stylesheets and helpers.js in the <head> section -->
    <!--? Config:  Mandatory theme config file contain global vars & default theme options, Set your preferred theme option in this file.  -->
    <script src="~/assets/js/config.js"></script>
</head>

<body>
    <!-- Layout wrapper -->
    <div class="layout-wrapper layout-content-navbar">
        <div class="layout-container">
            <!-- Menu -->

            <aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
                <div class="app-brand demo">
                    <a href="https://gitlab.com/telerik-teamwork-kk-ap/forum-management-system" class="app-brand-link">
                        <span class="app-brand-logo demo">
                            <img src="~/images/logo.png" width="25" height="25" />
                        </span>

                        <span class="app-brand-text demo menu-text fw-bolder ms-2">FMS</span>
                    </a>

                    <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
                        <i class="bx bx-chevron-left bx-sm align-middle"></i>
                    </a>
                </div>

                <div class="menu-inner-shadow"></div>

                <ul class="menu-inner py-1">
                    <!-- Dashboard -->
                    <li class="menu-item active">
                        <a asp-controller="Home" asp-action="Index" class="menu-link">
                            <i class="menu-icon tf-icons bx bx-home-circle"></i>
                            <div data-i18n="Analytics">Home</div>
                        </a>
                    </li>

                    <li class="menu-header small text-uppercase">
                        <span class="menu-header-text">Posts</span>
                    </li>

                    <!-- Layouts -->
                    <li class="menu-item">
                        <a asp-controller="Posts" asp-action="Index"
                           class="menu-link">
                            <i class="menu-icon tf-icons bx bx-file"></i>
                            <div data-i18n="Documentation">Posts</div>
                        </a>
                    </li>

                <li class="menu-header small text-uppercase">
                    <span class="menu-header-text">Users</span>
                </li>

                @{
                    if (!string.IsNullOrEmpty(currentUser))
                    {

                        <li class="menu-item">
                            <a href="javascript:void(0);" class="menu-link menu-toggle">
                                <i class="menu-icon tf-icons bx bx-dock-top"></i>
                                <div data-i18n="Account Settings">Account Settings</div>
                            </a>
                            <ul class="menu-sub">
                                <li class="menu-item">
                                    <a asp-controller="Users" asp-action="Details" class="menu-link">
                                        <div data-i18n="ViewDetails">View Details</div>
                                    </a>
                                </li>
                                <li class="menu-item">
                                    <a asp-controller="Users" asp-action="Edit" class="menu-link">
                                        <div data-i18n="EditProfile">Edit Profile</div>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="menu-item">
                            <a asp-controller="Users" asp-action="Index" class="menu-link">
                                <i class="menu-icon tf-icons bx bx-collection"></i>
                                <div data-i18n="Basic">Users List</div>
                            </a>
                        </li>


                        if (role == "admin")
                        {
                            <!-- Misc -->
                            <li class="menu-header small text-uppercase"><span class="menu-header-text">Admin Panel</span></li>
                            <li class="menu-item">
                                <a asp-controller="AdminPanel" asp-action="Index"
                                   class="menu-link">
                                    <i class="menu-icon tf-icons bx bx-support"></i>
                                    <div data-i18n="Support">Admins</div>
                                </a>
                            </li>

                        }

                    }
                }

                </ul>
            </aside>
            <!-- / Menu -->
            <!-- Layout container -->
            <div class="layout-page">

                <!-- Content wrapper -->
                <div class="content-wrapper">
                    @RenderBody()

                    <!-- Footer -->
                    <footer style="text-align:center">

                        <div>
                            © Copyright @DateTime.Now.Year,
                            <a href="https://gitlab.com/telerik-teamwork-kk-ap/forum-management-system" target="_blank" class="footer-link fw-bolder">KK-AP</a>
                            <br>
                            <br>

                        </div>
                    </footer>
                    <!-- / Footer -->

                    <div class="content-backdrop fade"></div>
                </div>
                <!-- Content wrapper -->
            </div>
            <!-- / Layout page -->
        </div>

        <!-- Overlay -->
        <div class="layout-overlay layout-menu-toggle"></div>
    </div>
    <!-- / Layout wrapper -->
    <!-- Login/Logout Button -->
    @{
        if (this.Context.Session.Keys.Any(k => k == "Username"))
        {
            <div class="buy-now">
                <a asp-controller="Authentication" asp-action="Logout" class="btn btn-danger btn-buy-now"><i class="bx bx-log-out-circle"></i> Logout</a>
            </div>
        }
        else
        {
            <div class="buy-now">
                <a asp-controller="Authentication" asp-action="Login"
                   class="btn btn-danger btn-buy-now">Login / Register</a>
            </div>
        }
    }
    <!-- / Login/Logout Button -->
    <!-- Core JS -->
    <!-- build:js assets/vendor/js/core.js -->
    <script src="~/assets/vendor/libs/jquery/jquery.js"></script>
    <script src="~/assets/vendor/libs/popper/popper.js"></script>
    <script src="~/assets/vendor/js/bootstrap.js"></script>
    <script src="~/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>

    <script src="~/assets/vendor/js/menu.js"></script>
    <!-- endbuild -->
    <!-- Vendors JS -->
    <script src="~/assets/vendor/libs/apex-charts/apexcharts.js"></script>

    <!-- Main JS -->
    <script src="~/assets/js/main.js"></script>

    <!-- Page JS -->
    <script src="~/assets/js/dashboards-analytics.js"></script>

    <!-- Place this tag in your head or just before your close body tag. -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>
</body>
</html>